fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    download_file: git://github.com/opentable/puppet-download_file.git
    wget: git://github.com/maestrodev/puppet-wget.git
  symlinks:
    teamcity: "#{source_dir}"
